# CONFIGURATION FILE

# how to use: write down only the thing you intend to use, leave blank all the others settings
# DATASET is the main folder
# GPU LIST is the list of gpu you intend to use, write -1 if you intend to use cpu
# MODEL TEMPLATE: model_name:{output_layers: [layers], reshape: [x,y]} in addition you CAN add the 'framework' tag to describe
# which framework you intend to use 'tensorflow'/'torch'


- dataset: 'C:\Users\User\OneDrive\Desktop\UNI\TESI\DatasetPerTest'
- gpu list: -1
- items:
    - visual:
        - input: 'inputVisual'
        - output: 'outputVisual'
        - model: {
            'ResNet50': { output_layers: [ 'avg_pool','conv5_block3_out' ], reshape: [ 224,224 ], framework: 'tensorflow' },
            'AlexNet': { output_layers: 5, reshape: [ 224,224 ] }
        }
    - textual:
        - input:
        - output:
        - model: {}
- interactions:
    - visual:
        - input:
        - output:
        - model: {}
    - textual:
        - input:
        - output:
        - model: {}
